language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm install chai
  - npm install --dev
  - npm install
  - npm install eslint
  - npm install -g jest
  - npm install -g codecov
  - npm install -g chai
  - npm install -g mocha
  - npm install -g standard
  - npm run testDependencies
  - echo "end of install"
script:
  - echo "end of script"
env:
  - HUSKY_SKIP_INSTALL=true
