#node -pe 'JSON.parse(process.argv[1]).foo' '{ "foo": "bar" }'

# test iban dependency
# cd ./node_modules/iban && npm test

# all dependencies:
# npm list --depth=0 --parseable=true > npm-list.log.txt
# only devDependencies:
# npm list --depth=0 --parseable=true --only=dev > npm-list.log.txt

# test
cd /Users/emmanuel/github/2019/id-validators && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@brazilian-utils/is-valid-boleto && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@brazilian-utils/validators && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@dgitals/rut && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@dr-kobros/fin-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@fczbkk/url-match && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@fczbkk/uuid4 && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@inforlabs/npm-typed && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@lykmapipo/phone && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@nelsonomuto/gender-info && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@open-source-uc/validate-uc-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@opuscapita/field-validators && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@reallyuseful/phonenumber && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/@willowi/validate-nif && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/aadhaar-validator && npm test && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/abnacn-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ae-codicefiscale && npm test
# cd /Users/emmanuel/github/2019/id-validators/node_modules/afip-cuit-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ahv13-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/arg.js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/au-bn-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/bark-js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/better-dni && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/birthdate-from-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/boy-girl && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/brazilian-values && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/card.js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/cc-luhn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/cedula-panama && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/chai && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/checkvat && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/china-id-card && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ci_node && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/cinovo-isin-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/clabe-check && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/cn-id-card-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/codemeli && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/codes-postaux && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/codice-fiscale-italiano && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/codice-fiscale-js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/container-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/country-emoji && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/countrydata && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/cpf-check && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/creditor-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/crypto-address-checker && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/cuit-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/currency-codes && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/current-week-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/danish-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/detect-all-gender && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/did-uri && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/dni-js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/dni-js-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/document-identifier-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/dutch-postcode-regex && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ecli-parser && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-config-airbnb-base && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-config-node && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-config-recommended && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-better && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-import && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-jasmine && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-jest && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-json && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-mocha && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-mocha-cleanup && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-node && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-objects && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-optimize-regex && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-perf-standard && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-sonarjs && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-this && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/eslint-plugin-unicorn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/estonian-bankreference && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/euro-banknote-serialnumber && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/fake-identity && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/fast-lei && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/fin-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/finnish-business-ids && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/finnish-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/fodselsnummer-generator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/french-phone-api && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/french-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/gender-detection && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/gender-es && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/genderify && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/gennames && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/gerador-validador-cpf && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/german-tax-id-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/greece-afm && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/greece-amka && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/greece-postal-code && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/greece-vehicle-plate && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/husky && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/i18n-iso-countries && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/id-is-valid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/id-pl && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/id-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/idcard-util && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identification-numbers && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identifiers-bibcode && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identifiers-doi && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identifiers-handle && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identifiers-nct && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identifiers-pubmed && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identifiers-urn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/identity-card-methods && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/imei && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/imsi-grok && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/in-interval && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/insee-municipality-code && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ipn-ua && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/iranian-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-aws-account-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-comparator-valid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-container && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-currency-code && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-github-url && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-okved-js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-birthdate && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-coordinate && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-coordinates && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-fodselsnummer && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-min-age && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-oib && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-orcid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-organization-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-valid-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/is-zero && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/isbn-utils && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/isikukood && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/iso-7064 && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/israeli-id-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/jest && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/jest-chain && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/jest-extended && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/jsvat && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/kennitala && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/lux-utils && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/math-interval-parser && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/medicare-provider-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/mobitel-iso-4217-currencies && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/module-alias && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/moment && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/mrz && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/mykad && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/napa && npm test
#cd /Users/emmanuel/github/2019/id-validators/node_modules/newtondev-mrz-parser && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/nic-info && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/nir-generator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/nir_validate && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/no-ssn-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/node-cmd && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/normalize-url && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/norway-postal-codes && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/norwegian-national-id-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/norwegian-validation && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/parse-cn-idcard && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/patch-package && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/persian-gender-detection && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/personal-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/personalausweis && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/pesel-check && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/phone-id.js && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/pl-numberplates && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/pl-registration-plate-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/polish-id-card-validate && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/postcode && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/pt-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/qing_random_idcard && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/repeating-interval && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/rodnecislo && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ru-names && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ru-validation-codes && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/russian-requisites-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/s10 && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/sa-id-gen && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/salesforce-id-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/se-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/short-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/short-unique-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/siren2tva && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/siret && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/social-insurance-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/south-africa-national-id-validation && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/south-african-id-info && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/south-african-id-parser && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/spanish-car-plate && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/ssn-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/string-gender && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/swe-validation && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/swiss-ssn-generator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/taiwan-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/taiwanid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/telephone-stuff && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/tfn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/thai-id-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/time-zone && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/tr-idnumbervalidator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/turkish-id && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/urn-lib && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/valid-url && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-cif && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-document-checker && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-edrpou && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-id-za && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-insz && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-medicare-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-nin && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-norwegian-ssn && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-polish && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate-polish-regon && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validate.io-interval && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validators-pl && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/validid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/vat-moss && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/vat-siren-siret && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/vehicle-registration-number && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/verifications && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/vin-generator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/vin-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/vindec-validator && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/woeid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/xvideos-valid && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/z1p && npm test
cd /Users/emmanuel/github/2019/id-validators/node_modules/za-id-validator && npm test
